# Eaglercraft Server Properties

# Maximum number of players
max-players=500

# Server logo
logo=universe

# Server description
# more updates soon
server-description="more updates soon"

# Spawn location
spawn-location=Kasandry Island