# Server Properties

# Game Modes Configurations

# Survival Mode
survival.enable=true

# Hardcore Mode
hardcore.enable=true

# Creative Mode
creative.enable=true

# Lifesteal Mode
lifesteal.enable=true

# Prison Mode
prison.enable=true

# Hide and Seek Mode
hideandseek.enable=true